#
#  Copyright (c) 2019 PANTHEON.tech s.r.o. All Rights Reserved.
#
#  This program and the accompanying materials are made available under the
#  terms of the Eclipse Public License v1.0 which accompanies this distribution,
#  and is available at https://www.eclipse.org/legal/epl-v10.html

- name: "Load list of configurations from supplied path"
  include_vars:
    file: "{{ cfg_list_source }}"
  when: cfg_list is not defined and cfg_list_source is defined

- fail:
    msg: "Configuration list not found or not defined. You can use cfg_list or cfg_list_source variables."
  when: current_host_cfg is not defined and cfg_list is not defined

- name: "Read list of configurations and store the configuration for the current host (by hostname)"
  set_fact:
    current_host_cfg: "{{ item }}"
  loop: "{{ cfg_list }}"
  when:
    - current_host_cfg is not defined
    - cfg_id is not defined
    - item.id == ansible_host

- name: "Read list of configurations and store the configuration for the current host (by cfg ID)"
  set_fact:
    current_host_cfg: "{{ item }}"
  loop: "{{ cfg_list }}"
  when:
    - current_host_cfg is not defined
    - cfg_id is defined
    - item.id == cfg_id

- name: "Read list of configurations and store the configuration for the current host (by tun_local_ip)"
  set_fact:
    current_host_cfg: "{{ item }}"
  loop: "{{ cfg_list }}"
  when:
    - current_host_cfg is not defined
    - cfg_id is not defined
    - item.tun_local_ip == ansible_host

- fail:
    msg: "Configuration not found or not defined. You can use cfg_id or current_host_cfg variables."
  when: current_host_cfg is not defined
