#
#  Copyright (c) 2019 PANTHEON.tech s.r.o. All Rights Reserved.
#
#  This program and the accompanying materials are made available under the
#  terms of the Eclipse Public License v1.0 which accompanies this distribution,
#  and is available at https://www.eclipse.org/legal/epl-v10.html


# Set up infrastructure including bridge(s) and links
- name: "Create network namespace"
  command: ip netns add "{{ current_host_cfg.server_name }}"
  args:
    creates: "/var/run/netns/{{ current_host_cfg.server_name }}"
  become: true

- name: "Crate veth interface"
  command: ip link add name "{{ current_host_cfg.server_veth }}" type veth peer name "{{ current_host_cfg.server_name }}"-"{{ current_host_cfg.server_veth }}"
  become: true

- name: "Connect veth interface to the namespace"
  command: ip link set dev "{{ current_host_cfg.server_veth }}" netns "{{ current_host_cfg.server_name }}"
  become: true

- name: "Set internal IP address to the veth in the namespace"
  command: ip netns exec "{{ current_host_cfg.server_name }}" ifconfig "{{ current_host_cfg.server_veth }}" "{{ current_host_cfg.server_ip }}"/24 up
  become: true

- name: "Set OVS to listen to OVSDB connections of SDN controller"
  command: ovs-vsctl set-manager ptcp:6640:"{{ current_host_cfg.tun_local_ip }}"
  become: true

- name: "Set port up"
  command: ip link set "{{ current_host_cfg.server_name }}"-"{{ current_host_cfg.server_veth }}" up
  become: true