#
#  Copyright (c) 2019 PANTHEON.tech s.r.o. All Rights Reserved.
#
#  This program and the accompanying materials are made available under the
#  terms of the Eclipse Public License v1.0 which accompanies this distribution,
#  and is available at https://www.eclipse.org/legal/epl-v10.html


- name: "Get the bridge id"
  retries: 3
  delay: 1
  register: ofp_ctx
  until: ofp_ctx.failed == False
  of_switch:
    controller_url: "{{ sdn_controller_url }}"
    bridge_name: "{{ current_host_cfg.bridge_name }}"
    cmd: "get_bridge_id"

- name: "Debug"
  debug:
    msg: 'The bridge ID: {{ ofp_ctx.br_id }}'