#
#  Copyright (c) 2020 PANTHEON.tech s.r.o. All Rights Reserved.
#
#  This program and the accompanying materials are made available under the
#  terms of the Eclipse Public License v1.0 which accompanies this distribution,
#  and is available at https://www.eclipse.org/legal/epl-v10.html


# Build a CBA archive and upload it into CDS
- hosts: localhost
  connection: local
  module_defaults:
    cds_controller:
      cds_url: "{{ cds_url | default('http://localhost:8000') }}"
      cds_auth_token: "{{ cds_auth_token | default('Y2NzZGthcHBzOmNjc2RrYXBwcw==') }}"
  roles:
    - role: gather_cba
    - role: upload_cba
