#
#  Copyright (c) 2020 PANTHEON.tech s.r.o. All Rights Reserved.
#
#  This program and the accompanying materials are made available under the
#  terms of the Eclipse Public License v1.0 which accompanies this distribution,
#  and is available at https://www.eclipse.org/legal/epl-v10.html

- name: "Resolve runtime root directory"
  include_role:
    name: resolve_runtime_root


- name: "Get local CBA tosca-meta"
  include_vars:
    file: "{{ cba_root }}/{{ cba_name }}/TOSCA-Metadata/TOSCA.meta"
    name: cba_local_tosca


- name: "Get local CBA definitions"
  include_vars:
    file: "{{ cba_root }}/{{ cba_name }}/{{ cba_local_tosca['Entry-Definitions'] }}"
    name: cba_local_definitions


- name: "Set blueprint name"
  set_fact:
    cba_blueprint: "{{ cba_local_definitions.metadata.template_name }}"
  when: cba_blueprint is not defined


- name: "Set blueprint version"
  set_fact:
    cba_version: "{{ cba_local_definitions.metadata.template_version }}"
  when: cba_version is not defined


- name: "Set CBA paths"
  set_fact:
    cba_directory: "{{ cba_root }}/{{ cba_name }}"
    cba_poor_archive: "{{ runtime_root_abs }}/{{ cba_name }}-{{ cba_version }}.zip"
    cba_rich_archive: "{{ runtime_root_abs }}/{{ cba_name }}-{{ cba_version }}.rich.zip"
