#
#  Copyright (c) 2019 PANTHEON.tech s.r.o. All Rights Reserved.
#
#  This program and the accompanying materials are made available under the
#  terms of the Eclipse Public License v1.0 which accompanies this distribution,
#  and is available at https://www.eclipse.org/legal/epl-v10.html


- name: "Create bridge in container"
  command: ip -netns "{{ net_ns_name }}" link add name br0 type bridge
  become: true

- name: "Set the bridge UP"
  command: ip -netns "{{ net_ns_name }}" link set dev br0 up
  become: true

- name: "Add interfaces into the bridge"
  command: ip -netns "{{ net_ns_name }}" link set dev "{{ item }}" master br0
  become: true
  loop: "{{ int_list }}"
