#
#  Copyright (c) 2019 PANTHEON.tech s.r.o. All Rights Reserved.
#
#  This program and the accompanying materials are made available under the
#  terms of the Eclipse Public License v1.0 which accompanies this distribution,
#  and is available at https://www.eclipse.org/legal/epl-v10.html


- name: "Get the OpenFlow bridge ID"
  include_role:
    name: resolve_of_bridge_id
# Doesn't work with include_role
#  ignore_errors: yes

- name: "Delete the flow 1"
  of_switch:
    controller_url: "{{ sdn_controller_url }}"
    bridge_id: "{{ ofp_ctx.br_id }}"
    cmd: "del_flow"
    flow_id: 1
  ignore_errors: yes

- name: "Delete the flow 2"
  of_switch:
    controller_url: "{{ sdn_controller_url }}"
    bridge_id: "{{ ofp_ctx.br_id }}"
    cmd: "del_flow"
    flow_id: 2
  ignore_errors: yes